version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tailadmin-laravel
    ports:
      - "8090:8000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - .:/var/www/tailadmin-laravel
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tailadmin
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

