version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yourdockerusername/julang_docker-tailadmin-laravel:beta
    container_name: laravel-app
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tailadmin
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:

