version: '3.8'

services:
  app:
    image: ${DOCKER_USER}/username_docker-tailadmin-laravel:beta
    build: .
    ports:
      - "8090:80"
    depends_on:
      - mysql
    networks:
      - tailadmin-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tailadmin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tailadmin-network

networks:
  tailadmin-network:

volumes:
  mysql_data:

