version: '3.8'
services:
  app:
    build:
      context: .
    image: ${{ secrets.DOCKER_USER }}/julang_docker-tailadmin-laravel:beta
    container_name: laravel-app
    ports:
      - "8090:8090"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: tailadmin
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:

