version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USER}/julang_docker-tailadmin-laravel:beta
      #    container_name: ${DOCKER_USER}/julang_docker-tailadmin-laravel:beta # baris ini sebelumnya dikomentari dan typo `container` harusnya `container_name`
    restart: unless-stopped
    tty: true
    environment: # typo: sebelumnya `enviroment`
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

