name: Deploy Laravel TailAdmin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/julang_docker-tailadmin-laravel:beta .
          docker push ${{ secrets.DOCKER_USER }}/julang_docker-tailadmin-laravel:beta

      - name: Run Docker Compose
        run: |
          export DOCKER_USER=${{ secrets.DOCKER_USER }}
          docker compose down
          docker compose up -d --build

