name: Laravel Inersia
run-name: Build, Push and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USER }}/julang_docker-tailadmin-laravel:beta
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  run-mysql:
    runs-on: self-hosted
    steps:
      - name: Start MySQL
        run: |
          docker run -d --name mysql-db \
            --network app-network \
            -e MYSQL_ROOT_PASSWORD=password \
            -e MYSQL_DATABASE=tailadmin \
            -p 3306:3306 \
            mysql:5.7

  build-push-image:
    needs: run-mysql
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t $IMAGE_NAME .

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push image
        run: docker push $IMAGE_NAME

  deploy:
    needs: build-push-image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stop containers
        run: docker compose down --remove-orphans || true

      - name: Start containers
        run: docker compose up -d

