name: Build, Push and Deploy Laravel App

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: "${{ secrets.DOCKER_USER }}julang_docker-tailadmin-laravel:beta"
  DOCKER_USER: "${{ secrets.DOCKER_USER }}"
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove old containers (optional)
        run: docker rm -f tailadmin-app mysql || true

      - name: Build image
        run: docker build -t $IMAGE_NAME .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push image to DockerHub
        run: docker push $IMAGE_NAME

      - name: Deploy with docker-compose
        run: docker compose up -d

