name: Laravel Inersia
run-name: Build, Push and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USER }}/docker-tailadmin-laravel:beta

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy:
    needs: build-push
    runs-on: self-hosted
    steps:
      - name: Stop existing containers
        run: docker compose down || true

      - name: Start containers
        run: docker compose up -d

