name: Laravel Deployment

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "${{ secrets.DOCKER_USER }}/tailadmin-laravel:beta"
  DOCKER_USER: "${{ secrets.DOCKER_USER }}"
  DOCKER_PASS: "${{ secrets.DOCKER_PASS }}"

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME

  deploy:
    needs: build-push
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull $IMAGE_NAME

      - name: Start containers with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d

