name: Laravel Inersia
run-name: Build, Push and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "${{ secrets.DOCKER_USER }}/julang_docker-tailadmin-laravel:beta"
  DOCKER_USER: "${{ secrets.DOCKER_USER }}"

jobs:
  build-push-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME

      - name: Stop & Remove Previous Containers
        run: docker compose down --rmi all || true

      - name: Start New Containers
        run: docker compose up -d

